### ISSUE TITLE
Question: can we activate the MRP - work order?

### ISSUE THREAD

**Issue by kittiu** [kittiu/aagc#10]
I understand we are not using it, but it something we can show customer as It is kinda cool.
As it will show the Planning by Production

![image](https://user-images.githubusercontent.com/1973598/75029753-3c9e5c80-54d5-11ea-844c-e4dea5c43831.png)

But when I try to activate, it shows me error when I click on menu Planning by work order / production.

WDYT?

**Comment by kittiu** [comment]
Here there the error if click at menu Manufacturing > Planning > Workorder > Planning by Workcenter
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/custom/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 752, in call_kw
    method = getattr(type(model), name)
AttributeError: type object 'mrp.workorder' has no attribute 'search_tasks'
```

**Comment by AaronHForgeFlow** [comment]
Hi @kittiu I will check. It seems it's something related to the gantt view. The gantt view installed is not enterprise one, it is one we developed. Probably I need to change it a bit to make it work with workorders.
