### ISSUE TITLE
Bug: error when click create "Manufacturing Order"

### ISSUE THREAD

**Issue by kittiu** [kittiu/aagc#12]
Note: I did activate "Work Order" and "MPS", not sure it related. But I did removed it, still have same error (I also never click create MO before).
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/custom/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5524, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5369, in _onchange_eval
    process(method_res)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5355, in process
    if res.get('value'):
AttributeError: 'bool' object has no attribute 'get'
```

**Comment by AaronHForgeFlow** [comment]
Workorders are ok to be added in this configurations. However, Odoo MPS is overlapping some features of the resource planning and MRP inventory, so I would deactivate that.
Currently, the best solution for planning for projects specifically and run MRP through all levels in a bill of materials is the combination of MRP multi level in OCA and using resource planing as demand
The problem of standard Odoo MRP is it does not go down trough the BOM of material to explode the MRP to the lower levels. 

In any case I will check the error because it should not fail.

Regards

**Comment by kittiu** [comment]
Ok, not on MPS. Thanks!

**Comment by kittiu** [comment]
@AaronHForgeFlow not sure this can be fixed?
Tomorrow, 27th, we will have a new customer to show project-expert, we will use this cust to rehearse.
And on 4th, we will present to AAGC.

Thanks a lot!
