### ISSUE TITLE
Questions: Product Bid Template, fields explaination

### ISSUE THREAD

**Issue by kittiu** [kittiu/aagc#6]
![Selection_250](https://user-images.githubusercontent.com/1973598/74709490-da81f500-5251-11ea-8e97-09ea90aa58a7.png)

**Comment by kittiu** [comment]
Also, when I click on 2 and 3, error occur,

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/custom/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 755, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 728, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 1385, in load_views
    for [v_id, v_type] in views
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 1385, in <dictcomp>
    for [v_id, v_type] in views
  File "/opt/odoo/auto/addons/stock/models/product.py", line 334, in fields_view_get
    res = super(Product, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/opt/odoo/auto/addons/mail/models/mail_thread.py", line 409, in fields_view_get
    res = super(MailThread, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 1471, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 1111, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 548, in raise_view_error
    raise ValueError(message)
ValueError: Field `is_cost_misaligned` does not exist

Error context:
View `n/a`
[view_id: n/a, xml_id: n/a, model: n/a, parent_id: n/a]
```

**Comment by AaronHForgeFlow** [comment]
Hi Kitti,

The Analytic Planning Journal serves as an attribute to classify the costs or revenue by the it's origin. It is equivalent to the Analytic Journal.

When adding planning costs to a project we are creating analytic plan lines (new model) The analytic planning lines are used to capture the planned cost or revenue, for a given planning version. They are equivalent to the analytic lines, used to capture the actual cost or revenue. The planning version is just a classification of planning lines. For example, the planned costs that comes from material will create analytic planning lines of planning version. Whereas  the planned cost coming form pure planning will go to another planning version, "Detailed" for example. That would help to analyze costs from different perspectives.

Regarding the error, that was due a module I had installed in the database but was not available in the server. I just uninstalled it. Sorry for that.

**Comment by kittiu** [comment]
IC, so it is used in similar way as to acocunt.analytic.line, but on the planning activities, right?

1. What window transaction that is used to generate these analytic.plan.line exactly?
2. Also, what is Project Success and Project Expense for? Are they part of the analytic.plan.line?

**Comment by AaronHForgeFlow** [comment]
> IC, so it is used in similar way as to acocunt.analytic.line, but on the planning activities, right?

Yes, exactly.

> 1. What window transaction that is used to generate these analytic.plan.line exactly?

Not sure if I understood the question. Analytic planning lines can be created:
- By hand: You can go to an analytic account and click on Action:
![image](https://user-images.githubusercontent.com/19620251/74720638-61c16f80-5236-11ea-9f53-e57e19d00731.png)
- By transferring them form the project bids
- By confirming resource plan. 

That is why analytic planning versions exists, that way you can classify the planning lines depending on where they came.

> 2. Also, what is Project Success and Project Expense for? Are they part of the analytic.plan.line?

Those are dummy products I created. It depends on the level of detail you want to have. For example, imagine a project that consists of building a bridge. You can create a product that is "The Bridge" and its value is $ 1,000,000.00. I can just create one analytic planning  line for this product. That means I expect $ 1,000,000.00 revenue coming from this product. Similar happens to costs. You can create a product that gathers all the planned cost, like "Bridge Material and Labor" for $700,000.00. Or, you can be more specific and drill down into more specific parts of the projects. It depends on the planner of the project.
